# Site settings
title: "Youngji Koh's Space"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Youngji Koh"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "youngji@kaist.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> Hello, World! I am Youngji Koh, a Ph.D. student in <a href='https://ic.kaist.ac.kr'>IC Lab</a> at KAIST.</p>
<p> My research focuses on observing users' routine behavior for gaining reflectiong their mental health. 
By understanding behavioral patterns and cognitive processes revealed through daily interactions with technology, 
I am dedicated to studying how these elements correlate with individuals' mental well-being. 
I develop intervention systems that are grounded in these observations, aiming to address mental health challenges in innovative ways. 
My goal is to promote mental wellness and encourage positive behavioral changes by implementing practical, technology-based interventions.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
resume_section_teaching:        true
resume_section_service:        true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_dribbble_url:          "mailto:youngji@kaist.ac.kr"
  resume_github_url:            "https://github.com/youngji-koh"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
